input_data <- read.csv2('data/household_power_consumption.csv', stringsAsFactors=FALSE, na.strings='?')
dates <- input_data$Date
times <- input_data$Time
dt <- paste(dates, times)
input_data$Time <- strptime(dt, "%d/%m/%Y %H:%M:%S")
input_data$Date <- as.Date(data$Date, "%d/%m/%Y")
rdata <- subset(input_data, Date >= '2007-02-01' & Date <= '2007-02-02')
rdata$Global_active_power <- as.numeric(rdata$Global_active_power)
rdata$Global_reactive_power <- as.numeric(rdata$Global_reactive_power)
rdata$Voltage <- as.numeric(rdata$Voltage)
rdata$Global_intensity <- as.numeric(rdata$Global_intensity)
rdata$Sub_metering_1 <- as.numeric(rdata$Sub_metering_1)
rdata$Sub_metering_2 <- as.numeric(rdata$Sub_metering_2)
rdata$Sub_metering_3 <- as.numeric(rdata$Sub_metering_3)
png(file='plot4.png', width=480, height=480)
par(mfrow = c(2,2))
with(rdata, plot(Time, Global_active_power, type='l', ylab='Global Active Power', xlab=''))
with(rdata, plot(Time, Voltage, type='l', ylab='Voltage', xlab='datetime'))
with(rdata, {plot(Time, Sub_metering_1, type='l', ylab='Energy sub metering', xlab='')
             points(Time, Sub_metering_2, type='l', col='red')
             points(Time, Sub_metering_3, type='l', col='blue')
             legend('topright', lty=1, col=c('black', 'red', 'blue'), legend=c(colnames(rdata)[7], colnames(rdata)[8], colnames(rdata)[9]), xjust=0, inset=0)
             })
with(rdata, plot(Time, Global_reactive_power, type='l', xlab='datetime'))
dev.off()